$schema: 'https://schema.getpostman.com/collection/v3'
$kind: environment
name: journalApp
values:
  - key: baseUrl
    value: 'http://localhost:8081/journal'
    type: default
    enabled: true
  - key: jwt
    value: ''
    type: secret
    enabled: true
  - key: entryId
    value: ''
    type: default
    enabled: true
  - key: city
    value: 'Mumbai'
    type: default
    enabled: true
